### PR TITLE
Return error when no activities are available to handle browser intent

### LINKED ISSUE #4: Don't crash when no browsers (or activities that can handle a URL) are installed on the device
### General information

* SDK/Library version: only with 2.10.0
* Environment: Production
* Android Version and Device: 
    - Samsung Galaxy J1 - OS 5.1.1
    - LG M1 - OS 5.1.1
    - LG Phoenix 2 - OS 6.0
    - Alcatel 5085C - OS 7.0

### Issue description

Follow up from: braintree/braintree_android/issues/195 reported by @simonlinj

When browser-switch-android tries to launch an `Intent` to open a URL on a device that has no activities that can open a URL it should report it as an error.

Original issue description:
Receiving a few crash reports after upgrading the SDK to 2.10.0. Had no issues on previews versions.

```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://assets.braintreegateway.com/mobile/three-d-secure-redirect/0.1.4/index.html?AcsUrl=https://0eaf.cardinalcommerce.com/EAFService/jsp/v1/redirect&PaReq=P.8ccf9XXXXXXXXX&TermUrl=https://api.braintreegateway.com:443/merchants/XXXXXXXX/client_api/v1/payment_methods/XXXXXXXXX/three_d_secure/authenticate?authorization_fingerprint=XXXXX&authorization_fingerprint_64=XXXXXXXXX&ReturnUrl=https://assets.braintreegateway.com/mobile/three-d-secure-redirect/0.1.4/redirect.html?redirect_url=XXX.XXXXX.XXXXXX.braintree://x-callback-url/braintree/threedsecure? flg=0x10000000 }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1404)
       at android.app.ContextImpl.startActivity(ContextImpl.java:1386)
       at android.content.ContextWrapper.startActivity(ContextWrapper.java:323)
       at com.braintreepayments.browserswitch.BrowserSwitchFragment.browserSwitch(BrowserSwitchFragment.java:137)
       at com.braintreepayments.browserswitch.BrowserSwitchFragment.browserSwitch(BrowserSwitchFragment.java:107)
       at com.braintreepayments.api.ThreeDSecure.launchBrowserSwitch(ThreeDSecure.java:218)
       at com.braintreepayments.api.ThreeDSecure.access$000(ThreeDSecure.java:35)
       at com.braintreepayments.api.ThreeDSecure$2$1.success(ThreeDSecure.java:153)
       at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:288)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

### PR DESCRIPTION
**Pull request by sdcoffey**
Fixes #4 

Adds a check to ensure that there is at least one activity available to handle the browser intent.

cc:
@quinnjn 
@bluk

### CODE REVIEW

File: browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java [hunk 1]
```diff
@@ -158,8 +163,19 @@ private boolean isReturnUrlSetup() {
...
+    }
+
+    private boolean activityAvailable(Intent intent) {
+        List<ResolveInfo> activities = availableActivities(intent);
+
+        return activities != null && activities.size() > 0;
+    }
+
+    private List<ResolveInfo> availableActivities(Intent intent) {
+        return mContext.getPackageManager()
```
Comment (quinnjn) [inline browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java]: We should always expect at least an empty list from this function. Sounds like `PackageManager#queryIntentActivities` does return an empty list.

>[If there are no matching activites, an empty list is returned](https://developer.android.com/reference/android/content/pm/PackageManager.html#queryIntentActivities(android.content.Intent,%20int))

File: browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java [hunk 2]
```diff
@@ -158,8 +163,19 @@ private boolean isReturnUrlSetup() {
                 .addCategory(Intent.CATEGORY_DEFAULT)
                 .addCategory(Intent.CATEGORY_BROWSABLE);
 
-        List<ResolveInfo> activities = mContext.getPackageManager()
+        List<ResolveInfo> availableActivities = availableActivities(intent);
+
+        return availableActivities != null && availableActivities.size() == 1;
```
Comment (quinnjn) [inline browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java]: I'm curious on why we are checking for exactly one activity here instead of `>0`

File: browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java [hunk 3]
```diff
@@ -131,6 +131,11 @@ public void browserSwitch(int requestCode, Intent intent) {
                             "information on setting up a return url scheme.");
             onBrowserSwitchResult(requestCode, result, null);
             return;
+        } else if (!activityAvailable(intent)) {
+            BrowserSwitchResult result = BrowserSwitchResult.ERROR
+                    .setErrorMessage(String.format("No activity available to handle browser switch intent %s", intent.getData().toString()));
```
Comment (quinnjn) [inline browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java]: I would simplify this even more.

> No installed activities can open this URL: %s

File: browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java (hunk 2 above)
Comment (sdcoffey) [reply browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java]: I think we expect there to be one and only one Activity that responds to the return url. I'm basing it off of the [error message we return](https://github.com/braintree/browser-switch-android/blob/master/browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java#L128), though.

Comment (quinnjn) [reply browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java]: Oh that makes sense 👍
